version: '2'
services:
  flaskapp-postgres:
    
    image: postgres:latest

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    
    ports:
      - 5432:5432

    volumes:
      - ./docker-initiate-initdb.d/init.sql:/flask-blogapp-poc/docker-initiate-initdb.d/10-init.sql
    
    expose:
    - "5432"

  web:

    build: .   

    ports:
      - 8090:8090
    
    volumes:
      - .:/flask-blogapp-poc
    
    depends_on:
      - flaskapp-postgres
      
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASS=admin123
      - DATABASE_HOST=flaskapp-postgres
      - DATABASE_PORT=5432

    expose:
    - "8090"