"""empty message

Revision ID: 1506e4688d12
Revises: cfc99c1a3bb1
Create Date: 2017-12-06 15:55:33.552099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1506e4688d12'
down_revision = 'cfc99c1a3bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('password', mysql.VARCHAR(length=192), nullable=False))
    # ### end Alembic commands ###
