"""empty message

Revision ID: 5e59a482a92f
Revises: 
Create Date: 2017-12-05 15:17:27.711366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e59a482a92f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_comment', sa.Column('comment_created_on', sa.DateTime(), nullable=True))
    op.drop_column('user_comment', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_comment', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_column('user_comment', 'comment_created_on')
    # ### end Alembic commands ###
