"""empty message

Revision ID: 7a1ee7bf393d
Revises: 1506e4688d12
Create Date: 2017-12-06 20:18:51.669211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1ee7bf393d'
down_revision = '1506e4688d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('password_hash', sa.String(length=192), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'password_hash')
    # ### end Alembic commands ###
