"""empty message

Revision ID: cfc99c1a3bb1
Revises: 5e59a482a92f
Create Date: 2017-12-06 13:22:05.370888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc99c1a3bb1'
down_revision = '5e59a482a92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('tokens', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'tokens')
    # ### end Alembic commands ###
